AppModelo/DevIO.UI.Site/Models/Aluno.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DevIO.UI.Site.Models
{
    public class Aluno
    {
        public Aluno()
        {
            Id = Guid.NewGuid();
        }
        public Guid Id { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public DateTime DataNascimento { get; set; }
        public string Teste { get; set; }
    }
}

AppModelo/DevIO.UI.Site/Models/Pedido.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DevIO.UI.Site.Models
{
    public class Pedido
    {
        public Guid Id { get; set; }

        public Pedido()
        {
            this.Id = Guid.NewGuid();
        }

    }
}

AppModelo/DevIO.UI.Site/Controllers/HomeController.cs
using DevIO.UI.Site.Data;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DevIO.UI.Site.Controllers
{
    public class HomeController : Controller
    {
        private readonly IPedidoRepository _pedidoRepository; //Teste no construtor
        private IPedidoRepository _pedidoRepository2; //Teste na action

        public HomeController(IPedidoRepository pedidoRepository)
        {
            _pedidoRepository = pedidoRepository;
        }

        public IActionResult Index()
        {
            var pedido = _pedidoRepository.ObterPedido();
            return View();
        }

        /*Apenas por fins de conhecimento, também é possível utilizar o FromService diretamente na Action, ao invés da chamada no construtor.
          Não sendo recomendado, apenas em situações muito específicas quando não se pode alterar um construtor, por exemplo.*/
        [Route("Index2")]
        [Route("[controller]/Index2")]
        public IActionResult Index2([FromServices] IPedidoRepository pedidoRepository2)
        {
            _pedidoRepository2 = pedidoRepository2;
            var pedido = _pedidoRepository.ObterPedido();
            return View("Index");
        }

    }
}

AppModelo/DevIO.UI.Site/Controllers/InjecoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DevIO.UI.Site.Services;
using Microsoft.AspNetCore.Mvc;

namespace DevIO.UI.Site.Controllers
{
    public class InjecoesController : Controller
    {
        public OperacaoService OperacaoService1 { get; }
        public OperacaoService OperacaoService2 { get; }

        public InjecoesController(OperacaoService operacaoService1, OperacaoService operacaoService2)
        {
            OperacaoService1 = operacaoService1;
            OperacaoService2 = operacaoService2;
        }

        public IActionResult Index()
        {
            string PrimeiraInstancia = "Primeira Instância" +
                                       "\nTransient: " + OperacaoService1.Transient.OperacaoID +
                                       "\nScoped: " + OperacaoService1.Scoped.OperacaoID +
                                       "\nSingleton: " + OperacaoService1.Singleton.OperacaoID +
                                       "\nSingleton Instance: " + OperacaoService1.SingletonInstance.OperacaoID;

            string SegundaInstancia = "\n\nSegunda Instância" +
                                        "\nTransient: " + OperacaoService2.Transient.OperacaoID +
                                        "\nScoped: " + OperacaoService2.Scoped.OperacaoID +
                                        "\nSingleton: " + OperacaoService2.Singleton.OperacaoID +
                                        "\nSingleton Instance: " + OperacaoService2.SingletonInstance.OperacaoID;

            
            string retorno = PrimeiraInstancia + Environment.NewLine + SegundaInstancia;
            return View(model: retorno);
        }
    }
}

AppModelo/DevIO.UI.Site/Controllers/TesteCrudController.cs
using DevIO.UI.Site.Data;
using DevIO.UI.Site.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DevIO.UI.Site.Controllers
{
    public class TesteCrudController : Controller
    {
        private readonly MeuDbContext _contexto;

        public TesteCrudController(MeuDbContext contexto)
        {
            _contexto = contexto;
        }

        public IActionResult Index()
        {
            var aluno = new Aluno()
            {
                Nome = "Rafael Nascimento",
                DataNascimento = DateTime.Now,
                Email = "rafael@teste.com.br"
            };

            //Add
            _contexto.Alunos.Add(aluno);
            _contexto.SaveChanges();

            //Buscar
            var aluno2 = _contexto.Alunos.Find(aluno.Id);
            var aluno3 = _contexto.Alunos.FirstOrDefault(a => a.Email == "rafael@teste.com.br");
            var alunos = _contexto.Alunos.Where(a => a.Nome == "Rafael");

            //Atualizar
            aluno.Nome = "Amanda";
            _contexto.Alunos.Update(aluno);
            _contexto.SaveChanges();
            
            //Remover
            _contexto.Alunos.Remove(aluno);
            _contexto.SaveChanges();

            return View();
        }
    }
}

AppModelo/DevIO.UI.Site/Views/Home/Index.cshtml
@using DevIO.UI.Site.Data
@inject IPedidoRepository TestePedidoRepository
@inject IPedidoRepository TestePedidoRepository2

<!--Dois injects apenas para ver a possibilidade de funcionamento de duas chamadas do @@inject-->
<!--Um teste apenas para utilizar todo o conceito de inject, caso seja necessário em alguma aplicação a chamada inject dentro da View, apesar de não ser nem um pouco recomendado, principalmente um repositório. -->

Olá <br />

Item 1: @TestePedidoRepository.ObterPedido().Id; <br />
Item 2: @TestePedidoRepository2.ObterPedido().Id;

AppModelo/DevIO.UI.Site/Views/Injecoes/Index.cshtml
@model string 
@{
    ViewData["Title"] = "Injeções";
}

<h1>Ciclo de Vida das Injeções</h1>

<p  style="white-space: pre-line">@Model</p>

AppModelo/DevIO.UI.Site/Views/Shared/_Layout.cshtml
<html>

<head>
    <title>@ViewData["Title"] - Minha App Modelo</title>

    @*<link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />*@
    <link href="~/lib/bootstrap/css/bootstrap-grid.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/css/bootstrap-reboot.css" rel="stylesheet" />
    <link href="~/css/site_bundle.min.css" rel="stylesheet" />
    <!--
        Posteriormente, incluir os Enviroment Include/Exclude
    -->
</head>

<body>
    <header>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AppModelo</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="Produtos" asp-controller="Cadastro" asp-action="Index">Cadastro de Produto</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="Vendas" asp-controller="Pedidos" asp-action="Index">Pedidos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Injecoes" asp-action="Index">Injeções</a>
                    </li>
                </ul>
            </div>
        </nav>

    </header>

    @RenderBody()

    <footer class="border-top footer text-muted">
        <div class="container">

            Minha App - <email>Contato</email> <span> | </span> <email email-domain="teste.io">Suporte</email> <span> | </span> <email>Atendimento</email>

        </div>
    </footer>

    @*<script src="~/lib/jquery/jquery.js"></script>*@
    <script src="~/lib/jquery-validate/localization/methods_pt.js"></script>
    <script src="~/lib/jquery-validate/additional-methods.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/js/site_bundle.min.js"></script>
    <!--
        Posteriormente, incluir os Enviroment Include/Exclude
    -->

</body>
</html>